import Layouts from "@/components/Layouts";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import Hireme from "@/components/Hireme";
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Edeh Johnpaul</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full dark:text-light min-h-screen">
        <Layouts className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image
                src={profilePic}
                alt="EdehJohnpaul"
                className="w-full h-auto"
                priority
                sizes="(max-width: 768px) 100vw,
                (max-width: 1200px) 50vw,
                50vw"
              />
            </div>

            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="Transforming Ideas into Digital Realities."
                className="!text-[2.7rem] !text-left"
              />
              <p className="my-4 text-base font-medium ">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications and also creating immersive digital experiences. Explore my latest
                projects, showcasing my expertise in React.js and
                web development.
              </p>

              <div className="flex items-center self-start mt-2">
                <Link
                  href="/dummy.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg 
                  font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark
                  dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light
                  "
                  download={true}
                >
                  Resume <LinkArrow className={'w-6 ml-1'}/>
                </Link>
                <Link href="mailto:edehjohnpaul@gmail.com" target={"_blank"}
                className="ml-4 text-lg font-medium capitalize underline dark:text-light text-dark"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layouts>
        <Hireme/>
        <div className="absolute right-8 bottom-8 inline-block w-14">
          <Image src={lightBulb} alt="Edehjohnpaul" className="w-full h-auto"/>
        </div>
      </main>
    </>
  );
}
